name: Simple CI with Cache

on: [push]

jobs:
  echo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: messages.txt
          key: ${{ runner.os }}-messages

      - name: Create messages file
        run: |
          echo "Hello from GitHub Actions CI/CD" > messages.txt
          echo "This is the second message from CI/CD..." >> messages.txt

      - name: Save cache
        uses: actions/cache@v4
        with:
          path: messages.txt
          key: ${{ runner.os }}-messages

