name: Simple CI

on: [push]

jobs:
  echo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello from GitHub Actions CI/CD"
        run: echo "This is the second messgae from CI/CD..."
